services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile
    ports: 
      - "3000:80"
    container_name: nepalgames
    restart: always
  
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports: 
      - "8000:8000"
    container_name: nepalgames_server
    environment:
      - DB_URL=postgres://ameesh:password@localhost:5432/nepal_games
    restart: always