name: gamesNepal_client
on: 
    push:
        branches:
            [ main ]
    pull_request:
        branches:
            [ main ]

jobs:
    lint-and-test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: |
                cd client
                npm install

            - name: run linter
              run: |
                cd client
                npm run lint

    server-test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Install dependencies
              run: |
                cd server
                npm install

            - name: run tests
              run: |
                cd server
                npm run test

                
    deploy:
        name: Deploy to AWS
        runs-on: ubuntu-latest
        needs: 
            - lint-and-test
            - server-test
        if: github.ref == 'refs/heads/main'
        steps:

          - name: connect to aws
            env: 
              EC2_HOST: ${{ secrets.EC2_HOST }}
              EC2_USERNAME: ${{ secrets.EC2_USER }}
              EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
            run: |
              echo "$EC2_PRIVATE_KEY" > github-ec2.pem
              chmod 600 github-ec2.pem
              ssh -o StrictHostKeyChecking=no -i github-ec2.pem $EC2_USERNAME@$EC2_HOST "

                  echo 'Checking NepalGames directory...'
                  if [ -d ~/NepalGames/.git ]; then
                      echo 'Directory exists. Pulling latest changes...'
                      cd ~/NepalGames
                      git pull origin main || echo 'Git pull failed!'
                  else
                      echo 'Directory does not exist. Cloning repository...'
                      git clone https://github.com/ameesh4/NepalGames.git ~/NepalGames || echo 'Git clone failed!'
                  fi
                  echo 'Navigating to client directory and building Docker image...'
                  sudo docker-compose build
                  echo 'Stopping and removing existing container...'
                  sudo docker-compose down
                  echo 'Starting new container...'
                  sudo docker-compose up -d
              "

          - name: Cleanup
            run: |
              rm github-ec2.pem